using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;
using DynamicData;
using Noggog;
using CommandLine;
using Mutagen.Bethesda.WPF.Reflection.Attributes;

namespace LastingSummonsPatcher
{
    public class TestSettings
    {
        //public double InitialCostMultiplier = 0.0;

        //public double LastingCostMultiplier = 1.0;

        public bool replaceSpells = true;

        [SettingName("Blacklisted FormKeys")]
        public List<string> blacklist = new();
    }

    public class Program
    {
        static Lazy<TestSettings> Settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "YourPatcher.esp")
                .Run(args);
        }


        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            //Your code here!

            List<string> blacklist = Settings.Value.blacklist;
            if (!state.LoadOrder.ModExists(new ModKey("MysticismMagic", ModType.Plugin), true))
            {
                blacklist.Add("07E5D5:Skyrim.esm"); // Flame Thrall
                blacklist.Add("07E5D6:Skyrim.esm"); // Frost Thrall
                blacklist.Add("07E5D7:Skyrim.esm"); // Storm Thrall
            }
            blacklist.Add("07E8DF:Skyrim.esm"); // Dead Thrall

            FormList drainSpellsListConjuration = new(state.PatchMod, "SustainedSpellsDrainListConjuration");
            FormList baseSpellsListConjuration = new(state.PatchMod, "SustainedSpellsBaseListConjuration");
            FormList lastingSpellsListConjuration = new(state.PatchMod, "SustainedSpellsEffectListConjuration");

            foreach (var magicEffectGetter in state.LoadOrder.PriorityOrder.MagicEffect().WinningOverrides())
            {
                if (magicEffectGetter.Flags.HasFlag(MagicEffect.Flag.Recover) && (magicEffectGetter.Archetype.Type == MagicEffectArchetype.TypeEnum.ValueModifier || magicEffectGetter.Archetype.Type == MagicEffectArchetype.TypeEnum.PeakValueModifier || magicEffectGetter.Archetype.Type == MagicEffectArchetype.TypeEnum.DualValueModifier))
                {
                    var magicEffect = magicEffectGetter.DeepCopy();
                    magicEffect.VirtualMachineAdapter ??= new();
                    if (magicEffectGetter.Archetype.ActorValue == ActorValue.Magicka || magicEffectGetter.SecondActorValue == ActorValue.Magicka)
                    {
                        if (magicEffectGetter.Flags.HasFlag(MagicEffect.Flag.Detrimental))
                        {
                            magicEffect.VirtualMachineAdapter.Scripts.Add(new ScriptEntry()
                            {
                                Flags = ScriptEntry.Flag.Local,
                                Name = "DispelSustainedSpellsStart",
                                Properties = new()
                                {
                                    new ScriptObjectProperty()
                                    {
                                        Flags = ScriptProperty.Flag.Edited,
                                        Name = "DispellSpell",
                                        Object = FormKey.Factory("000802:Sustained Spells.esp").ToLink<Spell>()
                                    }
                                }
                            });
                        }
                        else
                        {
                            magicEffect.VirtualMachineAdapter.Scripts.Add(new ScriptEntry()
                            {
                                Flags = ScriptEntry.Flag.Local,
                                Name = "DispelSustainedSpellsFinish",
                                Properties = new()
                                {
                                    new ScriptObjectProperty()
                                    {
                                        Flags = ScriptProperty.Flag.Edited,
                                        Name = "DispellSpell",
                                        Object = FormKey.Factory("000802:Sustained Spells.esp").ToLink<Spell>()
                                    }
                                }
                            });
                        }
                        state.PatchMod.MagicEffects.Set(magicEffect);
                    }

                    switch (magicEffectGetter.Archetype.ActorValue)
                    {
                        case ActorValue.ConjurationModifier:
                            magicEffect.VirtualMachineAdapter.Scripts.Add(new ScriptEntry()
                            {
                                Flags = ScriptEntry.Flag.Local,
                                Name = "SustainedSummonsRecalculateCosts",
                                Properties = new()
                                {
                                    new ScriptObjectProperty()
                                    {
                                        Flags = ScriptProperty.Flag.Edited,
                                        Name = "SustainedSpellsDrainList",
                                        Object = drainSpellsListConjuration.ToLink()
                                    },
                                    new ScriptObjectProperty()
                                    {
                                        Flags = ScriptProperty.Flag.Edited,
                                        Name = "SustainedSpellsBaseList",
                                        Object = baseSpellsListConjuration.ToLink()
                                    },
                                    new ScriptObjectProperty()
                                    {
                                        Flags = ScriptProperty.Flag.Edited,
                                        Name = "SustainedSpellsEffectList",
                                        Object = lastingSpellsListConjuration.ToLink()
                                    }
                                }
                            });
                            state.PatchMod.MagicEffects.Set(magicEffect);
                            break;
                    }
                    switch (magicEffectGetter.SecondActorValue)
                    {
                        case ActorValue.ConjurationModifier:
                            magicEffect.VirtualMachineAdapter.Scripts.Add(new ScriptEntry()
                            {
                                Flags = ScriptEntry.Flag.Local,
                                Name = "SustainedSummonsRecalculateCosts",
                                Properties = new()
                                {
                                    new ScriptObjectProperty()
                                    {
                                        Flags = ScriptProperty.Flag.Edited,
                                        Name = "SustainedSpellsDrainList",
                                        Object = drainSpellsListConjuration.ToLink()
                                    },
                                    new ScriptObjectProperty()
                                    {
                                        Flags = ScriptProperty.Flag.Edited,
                                        Name = "SustainedSpellsBaseList",
                                        Object = baseSpellsListConjuration.ToLink()
                                    },
                                    new ScriptObjectProperty()
                                    {
                                        Flags = ScriptProperty.Flag.Edited,
                                        Name = "SustainedSpellsEffectList",
                                        Object = lastingSpellsListConjuration.ToLink()
                                    }
                                }
                            });
                            state.PatchMod.MagicEffects.Set(magicEffect);
                            break;
                    }
                }
            }

            var drainEffectFlags = new MagicEffect.Flag();
            drainEffectFlags |= MagicEffect.Flag.Recover;
            drainEffectFlags |= MagicEffect.Flag.Detrimental;
            drainEffectFlags |= MagicEffect.Flag.NoHitEffect;
            drainEffectFlags |= MagicEffect.Flag.NoDuration;
            drainEffectFlags |= MagicEffect.Flag.NoArea;
            drainEffectFlags |= MagicEffect.Flag.Painless;

            var descriptionEffectFlags = new MagicEffect.Flag();
            descriptionEffectFlags |= MagicEffect.Flag.NoHitEffect;
            descriptionEffectFlags |= MagicEffect.Flag.NoHitEvent;
            descriptionEffectFlags |= MagicEffect.Flag.NoDuration;
            descriptionEffectFlags |= MagicEffect.Flag.NoArea;
            descriptionEffectFlags |= MagicEffect.Flag.NoMagnitude;

            foreach (var bookGetter in state.LoadOrder.PriorityOrder.Book().WinningOverrides())
            {
                if (bookGetter.Teaches is BookSpell spellGetter)
                {
                    var spell = spellGetter.Spell.Resolve(state.LinkCache);
                    if (blacklist.Contains(spell.FormKey.ToString())) continue;
                    var firstEffect = spell.Effects[0].BaseEffect.Resolve(state.LinkCache);
                    if (firstEffect.Archetype.Type == MagicEffectArchetype.TypeEnum.SummonCreature || firstEffect.Archetype.Type == MagicEffectArchetype.TypeEnum.Reanimate)
                    {
                        Console.WriteLine(spell.EditorID);
                        float longestChargeTime = 0;
                        var lastingSpell = spell.Duplicate(state.PatchMod.GetNextFormKey());
                        lastingSpell.EditorID = "SustainedSpell_" + lastingSpell.EditorID;
                        lastingSpell.Effects.Clear();
                        lastingSpell.Flags |= SpellDataFlag.NoDualCastModification;
                        lastingSpell.Keywords ??= new();
                        lastingSpell.Keywords.Add(FormKey.Factory("000800:Sustained Spells.esp"));

                        lastingSpellsListConjuration.Items.Add(lastingSpell);
                        baseSpellsListConjuration.Items.Add(spell);

                        /*
                        var global = new GlobalShort(state.PatchMod, "SustainedSpellGlobal_" + lastingSpell.EditorID);
                        state.PatchMod.Globals.Set(global);
                        */

                        string lastingSpellDescription = " Caster will have reduced magicka while this spell is active.";

                        MagicEffect drainEffect = new(state.PatchMod)
                        {
                            EditorID = "SustainedSpellDrainEffect_" + spell.EditorID,
                            Archetype = new MagicEffectArchetype() {
                                ActorValue = ActorValue.Magicka,
                                Type = MagicEffectArchetype.TypeEnum.ValueModifier
                            },
                            CastType = CastType.ConstantEffect,
                            CastingSoundLevel = SoundLevel.Silent,
                            Flags = drainEffectFlags,
                            Name = "Reduced Magicka",
                            Description = lastingSpellDescription
                        };
                        Spell drainSpell = new(state.PatchMod)
                        {
                            EditorID = "SustainedSpellDrain_" + spell.EditorID,
                            MenuDisplayObject = spell.MenuDisplayObject.AsNullable(),
                            Type = SpellType.Ability,
                            CastType = CastType.ConstantEffect,
                            TargetType = TargetType.Self,
                            Flags = SpellDataFlag.NoAbsorbOrReflect,
                            Name = lastingSpell.Name,
                            /*
                            Keywords = new()
                            {
                                sustainedSpellKeyword
                            },
                            */
                            Effects = new()
                            {
                                new Effect()
                                {
                                    BaseEffect = drainEffect.ToNullableLink<IMagicEffectGetter>(),
                                    Data = new()
                                }
                                /*
                                new Effect()
                                {
                                    BaseEffect = drainEffect.ToNullableLink<IMagicEffectGetter>(),
                                    Data = new(),
                                    Conditions = new Noggog.ExtendedList<Condition>()
                                    {
                                        new ConditionFloat()
                                        {
                                            CompareOperator = CompareOperator.EqualTo,
                                            ComparisonValue = 2,
                                            Data = new FunctionConditionData()
                                            {
                                                ParameterOneRecord = global.ToLink(),
                                                Function = Condition.Function.GetGlobalValue,
                                                RunOnType = Condition.RunOnType.Subject
                                            }
                                        }
                                    }
                                }
                                */
                            }
                        };
                        state.PatchMod.Spells.Set(drainSpell);
                        drainSpellsListConjuration.Items.Add(drainSpell);

                        foreach (var spellEffect in spell.Effects)
                        {
                            var lastingSpellEffect = spellEffect.DeepCopy();
                            lastingSpellEffect.Data ??= new();
                            lastingSpellEffect.Data.Duration = 86400;

                            var magicEffect = spellEffect.BaseEffect.Resolve(state.LinkCache);
                            if (magicEffect.SpellmakingCastingTime > longestChargeTime) longestChargeTime = magicEffect.SpellmakingCastingTime;
                            if (!magicEffect.Flags.HasFlag(MagicEffect.Flag.HideInUI))
                            {
                                var description = magicEffect.Description?.ToString();
                                if (description != null && description.Length > 0)
                                {
                                    lastingSpellDescription = description.Replace(" for <dur> seconds", "") + lastingSpellDescription;
                                }
                            }
                            if (magicEffect.Archetype.Type == MagicEffectArchetype.TypeEnum.SummonCreature || magicEffect.Archetype.Type == MagicEffectArchetype.TypeEnum.Reanimate)
                            {
                                var lastingMagicEffect = magicEffect.Duplicate(state.PatchMod.GetNextFormKey());
                                lastingSpellEffect.BaseEffect.SetTo(lastingMagicEffect);
                                lastingMagicEffect.EditorID = "SustainedSpellEffect_" + lastingMagicEffect.EditorID;
                                lastingMagicEffect.Flags |= MagicEffect.Flag.HideInUI;
                                //lastingMagicEffect.BaseCost = 0;
                                lastingMagicEffect.VirtualMachineAdapter ??= new();
                                lastingMagicEffect.VirtualMachineAdapter.Scripts.Add(new ScriptEntry()
                                {

                                    Flags = ScriptEntry.Flag.Local,
                                    Name = "SustainedSpell",
                                    Properties = new()
                                    {
                                        new ScriptObjectProperty()
                                        {
                                            Flags = ScriptProperty.Flag.Edited,
                                            Name = "basespell",
                                            Object = spell.ToLink()
                                        },
                                        new ScriptObjectProperty()
                                        {
                                            Flags = ScriptProperty.Flag.Edited,
                                            Name = "togglespellnegative",
                                            Object = drainSpell.ToLink()
                                        },
                                        new ScriptObjectProperty()
                                        {
                                            Flags = ScriptProperty.Flag.Edited,
                                            Name = "togglespelleffect",
                                            Object = lastingMagicEffect.ToLink()
                                        }
                                        /*
                                        new ScriptObjectProperty()
                                        {
                                            Flags = ScriptProperty.Flag.Edited,
                                            Name = "togglespellglobal",
                                            Object = global.ToLink<Global>()
                                        },
                                        new ScriptObjectProperty()
                                        {
                                            Flags = ScriptProperty.Flag.Edited,
                                            Name = "TwinSouls",
                                            Object = FormKey.Factory("0D5F1C:Skyrim.esm").ToLink<Perk>()
                                        },
                                        new ScriptFloatProperty()
                                        {
                                            Flags = ScriptProperty.Flag.Edited,
                                            Name = "spellxpmagnitude",
                                            Data = magicEffect.BaseCost * magicEffect.SkillUsageMultiplier
                                        },
                                        new ScriptObjectProperty()
                                        {
                                            Flags = ScriptProperty.Flag.Edited,
                                            Name = "PlayerRef",
                                            Object = FormKey.Factory("000014:Skyrim.esm").ToLink()
                                        }
                                        */
                                    }
                                });
                                state.PatchMod.MagicEffects.Set(lastingMagicEffect);
                            }
                            lastingSpell.Effects.Add(lastingSpellEffect);
                        }

                        var lastingSpellDescriptionEffect = new MagicEffect(state.PatchMod, "SustainedSpellDescription_" + lastingSpell.EditorID)
                        {
                            Description = lastingSpellDescription,
                            Archetype = new MagicEffectArchetype()
                            {
                                Type = MagicEffectArchetype.TypeEnum.Script,
                                ActorValue = ActorValue.None
                            },
                            CastingSoundLevel = SoundLevel.Silent,
                            CastType = CastType.FireAndForget,
                            TargetType = TargetType.TargetLocation,
                            Flags = descriptionEffectFlags
                        };
                        lastingSpell.Effects.Add(new Effect()
                        {
                            BaseEffect = lastingSpellDescriptionEffect.ToNullableLink<IMagicEffectGetter>(),
                            Data = new()
                        });
                        drainEffect.Description = lastingSpellDescription + " (<mag> Magicka)";


                        if (!lastingSpell.Flags.HasFlag(SpellDataFlag.ManualCostCalc))
                        {
                            lastingSpell.Flags |= SpellDataFlag.ManualCostCalc;
                            lastingSpell.ChargeTime = longestChargeTime;
                        }
                        //lastingSpell.BaseCost = 0;
                        state.PatchMod.Spells.Set(lastingSpell);
                        state.PatchMod.MagicEffects.Set(drainEffect);
                        state.PatchMod.MagicEffects.Set(lastingSpellDescriptionEffect);

                        var book = bookGetter.DeepCopy();
                        if (Settings.Value.replaceSpells)
                        {
                            book.Teaches = new BookSpell()
                            {
                                Spell = lastingSpell.ToLink()
                            };
                        } else
                        {
                            book.VirtualMachineAdapter ??= new();
                            book.VirtualMachineAdapter.Scripts.Add(new ScriptEntry()
                            {
                                Flags = ScriptEntry.Flag.Local,
                                Name = "LearnSpellonRead",
                                Properties = new()
                                {
                                    new ScriptObjectProperty()
                                    {
                                        Flags = ScriptProperty.Flag.Edited,
                                        Name = "SpellLearned",
                                        Object = lastingSpell.ToLink()
                                    }
                                }
                            });
                        }
                        state.PatchMod.Books.Set(book);
                    }
                }
            }

            if (Settings.Value.replaceSpells)
            {
                var mainQuest = state.LinkCache.Resolve<IQuestGetter>(FormKey.Factory("03372B:Skyrim.esm")).DeepCopy();
                if (mainQuest.VirtualMachineAdapter != null)
                {
                    foreach(var script in mainQuest.VirtualMachineAdapter.Scripts)
                    {
                        if (script.Name == "MQ101QuestScript")
                        {
                            foreach(var property in script.Properties)
                            {
                                if (property.Name == "ConjureFamiliar")
                                {
                                    foreach(var spell in baseSpellsListConjuration.Items)
                                    {
                                        if (spell.FormKey == FormKey.Factory("0640B6:Skyrim.esm"))
                                        {
                                            var objectProperty = (property as ScriptObjectProperty);
                                            if (objectProperty != null)
                                            {
                                                objectProperty.Object = (IFormLink<ISkyrimMajorRecordGetter>)lastingSpellsListConjuration.Items[baseSpellsListConjuration.Items.IndexOf(spell)];
                                                state.PatchMod.Quests.Set(mainQuest);
                                            }
                                        }
                                    }
                                }
                            }
                        }

                    }
                }
            }

            state.PatchMod.FormLists.Set(drainSpellsListConjuration);
            state.PatchMod.FormLists.Set(baseSpellsListConjuration);
            state.PatchMod.FormLists.Set(lastingSpellsListConjuration);
        }
    }
}